# Generated by Django 3.2.8 on 2021-11-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='costomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surename', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
