# Generated by Django 3.2.8 on 2021-11-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comentator'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentator',
            name='commen_mac',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
